# Generated by Django 5.2.7 on 2026-07-02 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_status'),
        ('user_settings', '0002_bill_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_settings.branch'),
            preserve_default=False,
        ),
    ]
