# Generated by Django 5.2.7 on 2026-07-03 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_branch'),
        ('user_settings', '0002_bill_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_settings.department'),
            preserve_default=False,
        ),
    ]
