# Generated by Django 5.2.7 on 2026-02-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_medicine_created_at_medicine_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
