# Generated by Django 5.2.7 on 2026-07-05 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_doctor_email_alter_doctor_phone'),
        ('user_settings', '0002_bill_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_settings.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_settings.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedures',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_settings.branch'),
            preserve_default=False,
        ),
    ]
