# Generated by Django 5.2.7 on 2026-06-05 15:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=100, unique=True)),
                ('bill_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('equipment', 'Equipment'), ('instrument', 'Instrument'), ('consumable', 'Consumable / Supply'), ('medicine', 'Medicine / Drug'), ('maintenance', 'Maintenance & Repair'), ('sterilization', 'Sterilization Supply'), ('xray', 'X-Ray / Imaging'), ('furniture', 'Furniture & Fixture'), ('software', 'Software / Subscription'), ('other', 'Other')], default='equipment', max_length=20)),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_contact', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Debit / Credit Card'), ('upi', 'UPI'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, help_text='Upload bill image (JPG/PNG) or PDF', null=True, upload_to='expenses/bills/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='user_settings.branch')),
            ],
            options={
                'ordering': ['-bill_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user_settings.bill')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
