# Generated by Django 5.2.7 on 2026-01-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.IntegerField()),
                ('aadhaar_id', models.BigIntegerField()),
                ('phno', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('pincode', models.CharField(max_length=20)),
                ('image_path', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
