# Generated by Django 5.2.7 on 2026-01-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_clinicalnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnotes',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
