# Generated by Django 5.2.7 on 2026-01-22 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_clinicalnotes_updated_at'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('discount_type', models.CharField(max_length=15)),
                ('discount', models.FloatField(default=0)),
                ('status', models.CharField(max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.procedures')),
            ],
        ),
    ]
