# Generated by Django 5.2.7 on 2026-02-16 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patientprocedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprocedure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprocedure',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
