# Generated by Django 5.2.7 on 2026-02-22 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patientprocedure_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_review_date', models.DateTimeField(blank=True, null=True)),
                ('medicine', models.CharField(max_length=150)),
                ('srength', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=100)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('duration_period', models.CharField(max_length=50)),
                ('morning', models.IntegerField(blank=True, null=True)),
                ('noon', models.IntegerField(blank=True, null=True)),
                ('night', models.IntegerField(blank=True, null=True)),
                ('after_food', models.BooleanField(default=True)),
                ('usage', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile')),
            ],
        ),
    ]
