# Generated by Django 5.2.7 on 2026-03-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprocedure',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
