# Generated by Django 5.2.7 on 2026-03-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patientprocedure_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='patients/'),
        ),
    ]
