# Generated by Django 5.2.7 on 2026-03-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_patientprofile_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='unit',
            new_name='strength_unit',
        ),
    ]
