# Generated by Django 5.2.7 on 2026-03-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_rename_unit_prescription_strength_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='srength',
            new_name='strength',
        ),
    ]
