# Generated by Django 5.2.7 on 2026-03-25 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_rename_srength_prescription_strength'),
        ('services', '0005_alter_doctor_email_alter_doctor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.medicine'),
        ),
    ]
