# Generated by Django 5.2.7 on 2026-03-26 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
