# Generated by Django 5.2.7 on 2026-03-31 15:35

import apps.patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='file',
            field=models.FileField(upload_to=apps.patients.models.patient_gallery_path),
        ),
    ]
