# Generated by Django 5.2.7 on 2026-06-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_alter_gallery_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
