# Generated by Django 5.2.7 on 2026-07-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_prescription_price_prescription_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
