# Generated by Django 5.2.7 on 2026-07-05 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_prescription_status'),
        ('user_settings', '0002_bill_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnotes',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_settings.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_settings.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprocedure',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_settings.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_settings.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_settings.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vital',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_settings.branch'),
            preserve_default=False,
        ),
    ]
