# Generated by Django 5.2.7 on 2026-07-07 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_bill_billitem'),
        ('user_settings', '0002_bill_billitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill',
            new_name='PatientBill',
        ),
        migrations.RenameModel(
            old_name='BillItem',
            new_name='PatientBillItem',
        ),
    ]
